### ISSUE TITLE
System freezes on copying files (with DOpus)

### ISSUE THREAD

**Issue by nexusle** [salass00/ssh2fs#1]
I'd tried this handler with two of my Linux servers. One a Raspberry with latest OS and one is a selfmade x86 (OpenMediaVault).

On both servers I can mount a folder, but copying files will let the system freeze after a few kilobytes. Please let me know, which informations you need to look into this issue.

Edit: 

Had tested now same things with PiStorm23 lite insteed of Icedrake. Same behavior.
Had also tested to copy files over Workbench directly and not with DOpus. Same behavior.

Tested connection with sshfs for Windows to the same targets. This works.

**Comment by salass00** [comment]
Which handler binary are you using (i386-aros or m68k-amigaos)?

For me the i386-aros binary does cause something like that, in that some operation will seem to hang  and then after a long time eventually return with LIBSSH2_ERROR_SOCKET_SEND (all subsequent operations then also failing with this error without the delay), however I haven't encountered any such issues while testing the m68k-amigaos binary on FS-UAE (testing includes running all diskspeed tests as well as copying a decent amount of files both ways).

**Comment by nexusle** [comment]
I use the m68k-handler. Will try it also in Win-/FS-UAE and report back.

**Comment by nexusle** [comment]
Could you please explain how you configured FS-UAE for testing? I had tried it also, but it seems that with the buildin bsdsocket.library emulation I can‘t get it to work.

**Comment by nexusle** [comment]
I had changed my TCP/IP-stack. With MiamiDX no problems. Seems Roadshow is to buggy.
